name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request_target:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # 소스코드를 체크아웃한다.
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      # JDK 17 를 준비한다.
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          
      # Android SDK 를 준비한다.
      -   name: Setup Android SDK
          uses: android-actions/setup-android@v2

      # gradlew 의 root 실행권한을 부여한다.
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Gradle 캐시 삭제
      - name: Clear Gradle Cache
        run: rm -rf ~/.gradle/caches ~/.gradle/wrapper ~/.gradle/daemon

      # Gradle 클린 빌드 실행
      - name: Clean and Build Gradle
        run: ./gradlew clean build --no-daemon --stacktrace

      
      # Gradle 을 빌드한다.
      - name: Build Gradle
        run: ./gradlew build --stacktrace

      # 테스트를 실행한다.
      - name: Run Test
        run: ./gradlew test
